export const SHOW_PRODUCT_INFO = "SHOW_PRODUCT_INFO";
export const CLOSE_PRODUCT_INFO = "CLOSE_PRODUCT_INFO";
export const SELECT_SERVICE = "SELECT_SERVICE";
export const CLEAR_SERVICE = "CLEAR_SERVICE";
